# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "anyMesh" do
  pod "AnyMesh", :path => "../"
end

target "anyMesh Tests" do
  pod "AnyMesh", :path => "../"

  pod 'AGAsyncTestHelper/Shorthand'
end

post_install do |installer_representation|
  installer_representation.project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ARCHS'] = 'armv7 armv7s'
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
    end
  end
end
